# Generated by Django 6.0.6 on 2026-06-23 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='Timestamp reported by the station', verbose_name='Recorded at')),
                ('raw_json', models.JSONField(blank=True, help_text='Raw API response for auditing and re-processing', null=True, verbose_name='Raw JSON')),
                ('ingested_at', models.DateTimeField(auto_now_add=True, help_text='When it was processed by the system', verbose_name='Ingested at')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='sensors.weatherstation', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Weather snapshot',
                'verbose_name_plural': 'Weather snapshots',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=4, help_text='Null if the data was empty or invalid from the source', max_digits=12, null=True, verbose_name='Value')),
                ('station_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='sensors.weatherstationvariableconfiguration', verbose_name='Station variable')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.weathersnapshot', verbose_name='Snapshot')),
            ],
            options={
                'verbose_name': 'Weather measurement',
                'verbose_name_plural': 'Weather measurements',
            },
        ),
        migrations.CreateModel(
            name='SensorMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Value')),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='Timestamp reported by the sensor', verbose_name='Recorded at')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received at server')),
                ('sensor_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='sensors.fieldsensorvariable', verbose_name='Sensor variable')),
            ],
            options={
                'verbose_name': 'Sensor measurement',
                'verbose_name_plural': 'Sensor measurements',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['sensor_variable', 'recorded_at'], name='measurement_sensor__720784_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='weathersnapshot',
            index=models.Index(fields=['station', 'recorded_at'], name='measurement_station_f21131_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weathersnapshot',
            unique_together={('station', 'recorded_at')},
        ),
        migrations.AddIndex(
            model_name='weathermeasurement',
            index=models.Index(fields=['station_variable', 'snapshot'], name='measurement_station_828b00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weathermeasurement',
            unique_together={('snapshot', 'station_variable')},
        ),
    ]
