# Generated by Django 6.0.3 on 2026-04-03 00:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([], blank=True, block_lookup={}, help_text='Contenido de la página principal', null=True)),
            ],
            options={
                'verbose_name': 'Página de inicio',
                'verbose_name_plural': 'Páginas de inicio',
            },
            bases=('wagtailcore.page',),
        ),
    ]
