# Generated by Django 6.0.3 on 2026-04-04 17:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la finca', max_length=100, verbose_name='Nombre')),
                ('address', models.CharField(help_text='Dirección de la finca', max_length=255, verbose_name='Dirección')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitud de la finca (Se puede obtener desde Google Maps)', max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitud de la finca (Se puede obtener desde Google Maps)', max_digits=9, verbose_name='Longitud')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización', verbose_name='Fecha de actualización')),
                ('owner', models.ForeignKey(help_text='Dueño de la finca', on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farmer.farmer', verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del lote', max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción del lote', verbose_name='Descripción')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Geometría del lote', null=True, srid=4326, verbose_name='Geometría')),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Centroide del lote', null=True, srid=4326, verbose_name='Centroide')),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, help_text='Área del lote en hectáreas', max_digits=10, null=True, verbose_name='Área (ha)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización', verbose_name='Fecha de actualización')),
                ('farm', models.ForeignKey(help_text='Finca a la que pertenece el lote', on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='farm.farm', verbose_name='Finca')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
