# Generated by Django 6.0.3 on 2026-04-04 17:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='longitude',
        ),
        migrations.AddField(
            model_name='farm',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Ubicación de la finca', null=True, srid=4326, verbose_name='Ubicación'),
        ),
    ]
