# Generated by Django 6.0.8 on 2026-08-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_remove_farm_latitude_remove_farm_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['name'], 'verbose_name': 'Finca', 'verbose_name_plural': 'Fincas'},
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'ordering': ['name'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
    ]
