# Generated by Django 6.0.8 on 2026-08-22 20:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_farm_options_alter_plot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Límite de la finca', null=True, srid=4326, verbose_name='Límite'),
        ),
    ]
