# Generated by Django 6.0.6 on 2026-06-23 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0002_remove_farm_latitude_remove_farm_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Outdoor temperature', max_length=100, unique=True, verbose_name='Name')),
                ('unit', models.CharField(help_text='Example: °C, %, mm, W/m²', max_length=20, verbose_name='Unit')),
                ('data_type', models.CharField(choices=[('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], default='float', max_length=10, verbose_name='Data type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Environment Variable',
                'verbose_name_plural': 'Environment Variables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Soil moisture sensor — North plot', max_length=100, verbose_name='Name')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('installed_at', models.DateField(blank=True, null=True, verbose_name='Installation date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('plot', models.ForeignKey(help_text='Plot where the sensor is physically installed', on_delete=django.db.models.deletion.CASCADE, related_name='field_sensors', to='farm.plot', verbose_name='Plot')),
            ],
            options={
                'verbose_name': 'Field sensor',
                'verbose_name_plural': 'Field sensors',
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: North field station', max_length=100, verbose_name='Name')),
                ('provider', models.CharField(choices=[('weatherlink', 'WeatherLink (Davis)'), ('wunderground', 'Weather Wunderground'), ('other', 'Other')], default='weatherlink', max_length=30, verbose_name='Provider')),
                ('station_id', models.CharField(help_text='Identifier on the provider platform', max_length=100, verbose_name='Station ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, help_text='Required by some providers such as WeatherLink v2', max_length=255, null=True, verbose_name='API Secret')),
                ('polling_interval_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Polling interval (min)')),
                ('is_active', models.BooleanField(default=True, help_text='Only active stations are polled by Celery', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('farm', models.ForeignKey(help_text='Farm this weather station belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='weather_stations', to='farm.farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Weather station',
                'verbose_name_plural': 'Weather stations',
            },
        ),
        migrations.CreateModel(
            name='FieldSensorVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_sensor_variables', to='sensors.environmentalvariable', verbose_name='Environmental variable')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_variables', to='sensors.fieldsensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Sensor variable',
                'verbose_name_plural': 'Sensor variables',
                'unique_together': {('sensor', 'env_variable')},
            },
        ),
        migrations.CreateModel(
            name='WeatherStationVariableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text='Exact field name in the API response. Example: "temp_out"', max_length=100, verbose_name='Field key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('env_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weather_station_variables', to='sensors.environmentalvariable', verbose_name='Environmental variable')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_variables', to='sensors.weatherstation', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Station variable',
                'verbose_name_plural': 'Station variables',
                'unique_together': {('station', 'env_variable'), ('station', 'field_key')},
            },
        ),
    ]
