# Generated by Django 6.0.6 on 2026-06-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_weathersnapshot_weathermeasurement_sensormeasurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalvariable',
            name='semantic_key',
            field=models.CharField(choices=[('soil_moisture', 'Soil moisture'), ('air_temperature', 'Air temperature'), ('solar_radiation', 'Solar radiation'), ('relative_humidity', 'Relative humidity'), ('other', 'Other')], default='other', help_text='Role of this variable in the system. The prediction engine uses this key to find the correct sensor automatically.', max_length=30, verbose_name='Semantic key'),
        ),
    ]
