# Generated by Django 6.0.3 on 2026-04-03 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, help_text='Email de contacto para la página', max_length=254, null=True, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, help_text='Teléfono de contacto para la página', max_length=20, null=True, verbose_name='Teléfono de contacto')),
                ('location', models.CharField(blank=True, help_text='Ubicación de la empresa', max_length=200, null=True, verbose_name='Ubicación')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='URL de Facebook', null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, help_text='URL de Twitter', null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, help_text='URL de Instagram', null=True, verbose_name='Instagram')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
