# Generated by Django 6.0.3 on 2026-04-02 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre de la organización', max_length=100, null=True)),
                ('nit', models.CharField(blank=True, help_text='Número de identificación tributaria de la organización', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la organización')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización de la organización')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Imagen de perfil del agricultor', null=True, upload_to='farmer/avatars/')),
                ('first_name', models.CharField(blank=True, help_text='Nombre del agricultor', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Apellido del agricultor', max_length=30, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PASSPORT', 'Pasaporte')], help_text='Tipo de documento de identificación del agricultor', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Género del agricultor', max_length=1, null=True)),
                ('document_number', models.CharField(blank=True, help_text='Número de documento de identificación del agricultor', max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Número de teléfono del agricultor', max_length=20, null=True)),
                ('city', models.CharField(blank=True, help_text='Ciudad de residencia del agricultor', max_length=50, null=True)),
                ('department', models.CharField(blank=True, help_text='Departamento de residencia del agricultor', max_length=50, null=True)),
                ('address', models.CharField(blank=True, help_text='Dirección de residencia del agricultor', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el agricultor está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del agricultor')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización del agricultor')),
                ('user', models.OneToOneField(help_text='Usuario asociado al agricultor', on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Opcional: Organización a la que pertenece el agricultor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='farmer.organization')),
            ],
        ),
    ]
