# Generated by Django 6.0.3 on 2026-04-04 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección de residencia del agricultor', max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del agricultor', null=True, upload_to='farmer/avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad de residencia del agricultor', max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='department',
            field=models.CharField(blank=True, help_text='Departamento de residencia del agricultor', max_length=50, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='document_number',
            field=models.CharField(blank=True, help_text='Número de documento de identificación del agricultor', max_length=20, null=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PASSPORT', 'Pasaporte')], help_text='Tipo de documento de identificación del agricultor', max_length=20, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='first_name',
            field=models.CharField(blank=True, help_text='Nombre del agricultor', max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Género del agricultor', max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el agricultor está activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='last_name',
            field=models.CharField(blank=True, help_text='Apellido del agricultor', max_length=30, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Opcional: Organización a la que pertenece el agricultor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='farmer.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Número de teléfono del agricultor', max_length=20, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(help_text='Usuario asociado al agricultor', on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
